### ISSUE TITLE
Fix pigpiod bug: can't play more than one script.

### ISSUE THREAD

**Issue by samjabrahams** [topherhooper/doctor_tank#8]
When using the C++ version of `pigpiod` (instead of the out-of-the-box C version), scripts can only be run once. It doesn't appear to be an issue WRT the C++ interfaces (namely `pigpiod_if2`), as scripts that use the C++ version run properly on the standard `pigpiod`.

Symptom: Scripts exit properly the first time they are run, and GPIO pins adjust as expected. If the script is run a second time, however, a connection is never initialized with the daemon.

**Comment by samjabrahams** [comment]
Note to self: Compile for debugging and attach `gdb` to running `pigpiod` instance when running a script.

**Comment by samjabrahams** [comment]
Discovery: the script hangs on the `recv` call [here](https://github.com/topherhooper/doctor_tank/blob/master/src/third_party/pigpio/src/pigpiod_if2.cpp#L160), but only after the first time it runs. Will need to look into socket allocation/management and whatnot.

**Comment by samjabrahams** [comment]
https://stackoverflow.com/questions/1887668/socket-programming-c-c-recv-function-hangs

**Comment by samjabrahams** [comment]
Socket handler:

https://github.com/topherhooper/doctor_tank/blob/master/src/third_party/pigpio/src/pigpio.cpp#L6870-L6988

**Comment by samjabrahams** [comment]
`pthSocketThreadHandler` called by [`pthSocketThread`](https://github.com/topherhooper/doctor_tank/blob/master/src/third_party/pigpio/src/pigpio.cpp#L7011-L7069), which is called by [`initInitialise`](https://github.com/topherhooper/doctor_tank/blob/master/src/third_party/pigpio/src/pigpio.cpp#L8025-L8198) which is called by [`gpioInitialise`](https://github.com/topherhooper/doctor_tank/blob/master/src/third_party/pigpio/src/pigpio.cpp#L8427)

**Comment by samjabrahams** [comment]
On a successful run, the `pigpiod` daemon is able to call [`gpioNotifyOpenInBand`](https://github.com/topherhooper/doctor_tank/blob/master/src/third_party/pigpio/src/pigpio.cpp#L11600) (with [`PI_CMD_NOIB`](https://github.com/topherhooper/doctor_tank/blob/master/src/third_party/pigpio/src/pigpio.cpp#L6925) as the first signal. Then it loops through various commands [here](https://github.com/topherhooper/doctor_tank/blob/master/src/third_party/pigpio/src/pigpio.cpp#L6946).

**Comment by samjabrahams** [comment]
It looks like the second time a process attempts to start running, the `pthSocketThread` segfaults.

**Comment by samjabrahams** [comment]
GDB backtrace of the `pthSocketThread` when it segfaults:

```
#0  __libc_siglongjmp (env=env@entry=0x763e8e90, val=val@entry=1) at longjmp.c:30
#1  0x76e62f20 in unwind_stop (version=<optimized out>, actions=<optimized out>,
    exc_class=<optimized out>, exc_obj=<optimized out>, context=0x763e8550,
    stop_parameter=0x763e8e90) at unwind.c:94
#2  0x76e456a8 in ?? () from /lib/arm-linux-gnueabihf/libgcc_s.so.1
#3  0x76e4607a in _Unwind_ForcedUnwind () from /lib/arm-linux-gnueabihf/libgcc_s.so.1
#4  0x76e62fd2 in __GI___pthread_unwind (buf=<optimized out>) at unwind.c:121
#5  0x76e630fc in __do_cancel () at pthreadP.h:283
#6  __pthread_enable_asynccancel () at cancellation.c:49
#7  0x76e5d468 in pthread_join (threadid=1983812720, thread_return=0x0) at pthread_join.c:65
#8  0x76ed3e26 in pigpio::initReleaseResources ()
    at /home/pi/doctor_tank/src/third_party/pigpio/src/pigpio.cpp:7899
#9  0x76ed57f6 in pigpio::gpioTerminate ()
    at /home/pi/doctor_tank/src/third_party/pigpio/src/pigpio.cpp:8514
#10 0x76ecd02a in pigpio::sigHandler (signum=11)
    at /home/pi/doctor_tank/src/third_party/pigpio/src/pigpio.cpp:5484
#11 <signal handler called>
#12 0x76e5c9d2 in get_cached_stack (memp=<synthetic pointer>, sizep=<synthetic pointer>)
    at allocatestack.c:236
#13 allocate_stack (stack=<synthetic pointer>, pdp=<synthetic pointer>, attr=0x763e8dc8)
    at allocatestack.c:501
#14 __pthread_create_2_1 (newthread=0x763e8db0, attr=0x76fc9000, start_routine=0x0, arg=0x7ee66530)
    at pthread_create.c:539
#15 0x76ed1844 in pigpio::pthSocketThread (x=0x7ee664ec)
    at /home/pi/doctor_tank/src/third_party/pigpio/src/pigpio.cpp:7055
#16 0x76e5c5b4 in start_thread (arg=0x0) at pthread_create.c:335
#17 0x76dd5c4c in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:89
   from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
